# Generated by Django 4.0.3 on 2022-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='book name')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='author')),
            ],
        ),
    ]
